<a href="https://colab.research.google.com/github/FtovaVS/CoderhouseDataScienceI/blob/main/Entrega2.1_FrancoVallone_Coder_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("/content/drive/MyDrive/Coderhouse - Data Science I/vgsales-12-4-2019-short.csv")

In [6]:
df.head()

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer,Critic_Score,User_Score,Total_Shipped,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,82.86,NaN,NaN,NaN,NaN,NaN,2006.0
1,2,Super Mario Bros.,Platform,NaN,NES,Nintendo,Nintendo EAD,10.0,NaN,40.24,NaN,NaN,NaN,NaN,NaN,1985.0
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,37.14,NaN,NaN,NaN,NaN,NaN,2008.0
3,4,PlayerUnknown's Battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,36.60,NaN,NaN,NaN,NaN,NaN,2017.0
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,33.09,NaN,NaN,NaN,NaN,NaN,2009.0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55792 entries, 0 to 55791
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Rank                         55792 non-null  int64
 1   Name                         55792 non-null  object
 2   Genre                        55792 non-null  object
 3   ESRB_Rating                  23623 non-null  object
 4   Platform                     55792 non-null  object
 5   Publisher                    55792 non-null  object
 6   Developer                    55775 non-null  object
 7   Critic_Score                 6536 non-null   float64
 8   User_Score                   335 non-null    float64
 9   Total_Shipped                1827 non-null   float64
 10  Global_Sales                 19415 non-null  float64
 11  NA_Sales                     12964 non-null  float64
 12  PAL_Sales                    13189 non-null  float64
 13  JP_Sales                     7043 non-null   float64
 14  Other_Sales                  15522 non-null  float64
 15  Year                         55792 non-null  object
 16  Recomendado_por_la_critica?  55792 non-null  object
 17  Apto_para_todo_publico?      55792 non-null  object
dtypes: float64(8), int64(1), object(9)
memory usage: 7.7+ MB

In [18]:
df.shape

(55792, 18)

In [7]:
df.describe()

,Rank,Critic_Score,User_Score,Total_Shipped,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year
count,55792.000000,6536.000000,335.000000,1827.000000,19415.000000,12964.000000,13189.000000,7043.000000,15522.000000,54813.000000
mean,27896.500000,7.213709,8.253433,1.887258,0.365503,0.275541,0.155263,0.110402,0.044719,2005.659095
std,16105.907446,1.454079,1.401489,4.195693,0.833022,0.512809,0.399257,0.184673,0.129554,8.355585
min,1.000000,1.000000,2.000000,0.030000,0.000000,0.000000,0.000000,0.000000,0.000000,1970.000000
25%,13948.750000,6.400000,7.800000,0.200000,0.030000,0.050000,0.010000,0.020000,0.000000,2000.000000
50%,27896.500000,7.500000,8.500000,0.590000,0.120000,0.120000,0.040000,0.050000,0.010000,2008.000000
75%,41844.250000,8.300000,9.100000,1.800000,0.360000,0.290000,0.140000,0.120000,0.040000,2011.000000
max,55792.000000,10.000000,10.000000,82.860000,20.320000,9.760000,9.850000,2.690000,3.120000,2020.000000

#Hallazgos:

###Detecto que la columna Year esta como número con decimales cuando debería ser fecha o string.

###Global sales tiene mucha mayor cantidad de registros dando a entender que hay muchos mas videojuegos que no se lanzaron en formato físico (Diferencia con Total Shipped)

In [8]:
display(df.dtypes)

Rank               int64
Name              object
Genre             object
ESRB_Rating       object
Platform          object
Publisher         object
Developer         object
Critic_Score     float64
User_Score       float64
Total_Shipped    float64
Global_Sales     float64
NA_Sales         float64
PAL_Sales        float64
JP_Sales         float64
Other_Sales      float64
Year             float64
dtype: object

In [9]:
#Modifico la columna Year para que figure como string

df['Year'] = df['Year'].astype(str)

In [10]:
display(df.dtypes)

Rank               int64
Name              object
Genre             object
ESRB_Rating       object
Platform          object
Publisher         object
Developer         object
Critic_Score     float64
User_Score       float64
Total_Shipped    float64
Global_Sales     float64
NA_Sales         float64
PAL_Sales        float64
JP_Sales         float64
Other_Sales      float64
Year              object
dtype: object

In [11]:
# Calculo el porcentaje de nulos por columna
porcentaje_nulos = df.isnull().mean() * 100

print(porcentaje_nulos)

Rank              0.000000
Name              0.000000
Genre             0.000000
ESRB_Rating      57.658804
Platform          0.000000
Publisher         0.000000
Developer         0.030470
Critic_Score     88.285059
User_Score       99.399555
Total_Shipped    96.725337
Global_Sales     65.201104
NA_Sales         76.763694
PAL_Sales        76.360410
JP_Sales         87.376326
Other_Sales      72.178807
Year              0.000000
dtype: float64

In [12]:
def recomendado(puntaje):
    if pd.isna(puntaje):
        return 'Sin Calificar'
    if puntaje >= 6.0:
        return 'Recomendado'
    elif puntaje < 6.0:
        return 'No Recomendado'

df['Recomendado_por_la_critica?'] = df['Critic_Score'].apply(recomendado)

In [13]:
#Pruebo a ver la nueva columna
df.head()

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer,Critic_Score,User_Score,Total_Shipped,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year,Recomendado_por_la_critica?
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,82.86,NaN,NaN,NaN,NaN,NaN,2006.0,Recomendado
1,2,Super Mario Bros.,Platform,NaN,NES,Nintendo,Nintendo EAD,10.0,NaN,40.24,NaN,NaN,NaN,NaN,NaN,1985.0,Recomendado
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,37.14,NaN,NaN,NaN,NaN,NaN,2008.0,Recomendado
3,4,PlayerUnknown's Battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,36.60,NaN,NaN,NaN,NaN,NaN,2017.0,Sin Calificar
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,33.09,NaN,NaN,NaN,NaN,NaN,2009.0,Recomendado

In [14]:
#Creo columna donde si el raiting es E significa que es apto para todo público

df['Apto_para_todo_publico?'] = df['ESRB_Rating'].apply(lambda x: 'Si' if x == 'E' else 'No')

In [15]:
df.head()

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer,Critic_Score,User_Score,Total_Shipped,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year,Recomendado_por_la_critica?,Apto_para_todo_publico?
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,82.86,NaN,NaN,NaN,NaN,NaN,2006.0,Recomendado,Si
1,2,Super Mario Bros.,Platform,NaN,NES,Nintendo,Nintendo EAD,10.0,NaN,40.24,NaN,NaN,NaN,NaN,NaN,1985.0,Recomendado,No
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,37.14,NaN,NaN,NaN,NaN,NaN,2008.0,Recomendado,Si
3,4,PlayerUnknown's Battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,36.60,NaN,NaN,NaN,NaN,NaN,2017.0,Sin Calificar,No
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,33.09,NaN,NaN,NaN,NaN,NaN,2009.0,Recomendado,Si