<a href="https://colab.research.google.com/github/FtovaVS/CoderhouseDataScienceI/blob/main/Vallone_Franco_Checkpoint3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Coderhouse - Data Science I/vgsales-12-4-2019-short.csv")

In [3]:
df.head()

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer,Critic_Score,User_Score,Total_Shipped,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,82.86,NaN,NaN,NaN,NaN,NaN,2006.0
1,2,Super Mario Bros.,Platform,NaN,NES,Nintendo,Nintendo EAD,10.0,NaN,40.24,NaN,NaN,NaN,NaN,NaN,1985.0
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,37.14,NaN,NaN,NaN,NaN,NaN,2008.0
3,4,PlayerUnknown's Battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,36.60,NaN,NaN,NaN,NaN,NaN,2017.0
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,33.09,NaN,NaN,NaN,NaN,NaN,2009.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55792 entries, 0 to 55791
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           55792 non-null  int64
 1   Name           55792 non-null  object
 2   Genre          55792 non-null  object
 3   ESRB_Rating    23623 non-null  object
 4   Platform       55792 non-null  object
 5   Publisher      55792 non-null  object
 6   Developer      55775 non-null  object
 7   Critic_Score   6536 non-null   float64
 8   User_Score     335 non-null    float64
 9   Total_Shipped  1827 non-null   float64
 10  Global_Sales   19415 non-null  float64
 11  NA_Sales       12964 non-null  float64
 12  PAL_Sales      13189 non-null  float64
 13  JP_Sales       7043 non-null   float64
 14  Other_Sales    15522 non-null  float64
 15  Year           54813 non-null  float64
dtypes: float64(9), int64(1), object(6)
memory usage: 6.8+ MB

In [5]:
df.shape

(55792, 16)

In [6]:
df.describe()

,Rank,Critic_Score,User_Score,Total_Shipped,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year
count,55792.000000,6536.000000,335.000000,1827.000000,19415.000000,12964.000000,13189.000000,7043.000000,15522.000000,54813.000000
mean,27896.500000,7.213709,8.253433,1.887258,0.365503,0.275541,0.155263,0.110402,0.044719,2005.659095
std,16105.907446,1.454079,1.401489,4.195693,0.833022,0.512809,0.399257,0.184673,0.129554,8.355585
min,1.000000,1.000000,2.000000,0.030000,0.000000,0.000000,0.000000,0.000000,0.000000,1970.000000
25%,13948.750000,6.400000,7.800000,0.200000,0.030000,0.050000,0.010000,0.020000,0.000000,2000.000000
50%,27896.500000,7.500000,8.500000,0.590000,0.120000,0.120000,0.040000,0.050000,0.010000,2008.000000
75%,41844.250000,8.300000,9.100000,1.800000,0.360000,0.290000,0.140000,0.120000,0.040000,2011.000000
max,55792.000000,10.000000,10.000000,82.860000,20.320000,9.760000,9.850000,2.690000,3.120000,2020.000000

#Hallazgos:

###Detecto que la columna Year esta como número con decimales cuando debería ser fecha o string.

###Global sales tiene mucha mayor cantidad de registros dando a entender que hay muchos mas videojuegos que no se lanzaron en formato físico (Diferencia con Total Shipped)

In [7]:
display(df.dtypes)

Rank               int64
Name              object
Genre             object
ESRB_Rating       object
Platform          object
Publisher         object
Developer         object
Critic_Score     float64
User_Score       float64
Total_Shipped    float64
Global_Sales     float64
NA_Sales         float64
PAL_Sales        float64
JP_Sales         float64
Other_Sales      float64
Year             float64
dtype: object

In [8]:
display(df.dtypes)

Rank               int64
Name              object
Genre             object
ESRB_Rating       object
Platform          object
Publisher         object
Developer         object
Critic_Score     float64
User_Score       float64
Total_Shipped    float64
Global_Sales     float64
NA_Sales         float64
PAL_Sales        float64
JP_Sales         float64
Other_Sales      float64
Year             float64
dtype: object

In [9]:
# Calculo el porcentaje de nulos por columna
porcentaje_nulos = df.isnull().mean() * 100

print(porcentaje_nulos)

Rank              0.000000
Name              0.000000
Genre             0.000000
ESRB_Rating      57.658804
Platform          0.000000
Publisher         0.000000
Developer         0.030470
Critic_Score     88.285059
User_Score       99.399555
Total_Shipped    96.725337
Global_Sales     65.201104
NA_Sales         76.763694
PAL_Sales        76.360410
JP_Sales         87.376326
Other_Sales      72.178807
Year              1.754732
dtype: float64

In [10]:
#Ordeno por porcentaje de valores nulos

porcentaje_nulos.sort_values(ascending=False)

User_Score       99.399555
Total_Shipped    96.725337
Critic_Score     88.285059
JP_Sales         87.376326
NA_Sales         76.763694
PAL_Sales        76.360410
Other_Sales      72.178807
Global_Sales     65.201104
ESRB_Rating      57.658804
Year              1.754732
Developer         0.030470
Platform          0.000000
Rank              0.000000
Publisher         0.000000
Name              0.000000
Genre             0.000000
dtype: float64

In [11]:
def recomendado(puntaje):
    if pd.isna(puntaje):
        return 'Sin Calificar'
    if puntaje >= 6.0:
        return 'Recomendado'
    elif puntaje < 6.0:
        return 'No Recomendado'

df['Recomendado_por_la_critica?'] = df['Critic_Score'].apply(recomendado)

In [12]:
#Pruebo a ver la nueva columna
df.head()

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer,Critic_Score,User_Score,Total_Shipped,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year,Recomendado_por_la_critica?
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,82.86,NaN,NaN,NaN,NaN,NaN,2006.0,Recomendado
1,2,Super Mario Bros.,Platform,NaN,NES,Nintendo,Nintendo EAD,10.0,NaN,40.24,NaN,NaN,NaN,NaN,NaN,1985.0,Recomendado
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,37.14,NaN,NaN,NaN,NaN,NaN,2008.0,Recomendado
3,4,PlayerUnknown's Battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,36.60,NaN,NaN,NaN,NaN,NaN,2017.0,Sin Calificar
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,33.09,NaN,NaN,NaN,NaN,NaN,2009.0,Recomendado

In [13]:
#Creo columna donde si el raiting es E significa que es apto para todo público

df['Apto_para_todo_publico?'] = df['ESRB_Rating'].apply(lambda x: 'Si' if x == 'E' else 'No')

In [14]:
df.head()

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer,Critic_Score,User_Score,Total_Shipped,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year,Recomendado_por_la_critica?,Apto_para_todo_publico?
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,82.86,NaN,NaN,NaN,NaN,NaN,2006.0,Recomendado,Si
1,2,Super Mario Bros.,Platform,NaN,NES,Nintendo,Nintendo EAD,10.0,NaN,40.24,NaN,NaN,NaN,NaN,NaN,1985.0,Recomendado,No
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,37.14,NaN,NaN,NaN,NaN,NaN,2008.0,Recomendado,Si
3,4,PlayerUnknown's Battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,36.60,NaN,NaN,NaN,NaN,NaN,2017.0,Sin Calificar,No
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,33.09,NaN,NaN,NaN,NaN,NaN,2009.0,Recomendado,Si

# Entrega 3
(Se agregó df.info(), df.shape() y el orden de los porcentajes de valores nulos en la parte superior para completar correctamente la 2da entrega.

In [15]:
df.head()

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer,Critic_Score,User_Score,Total_Shipped,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year,Recomendado_por_la_critica?,Apto_para_todo_publico?
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,82.86,NaN,NaN,NaN,NaN,NaN,2006.0,Recomendado,Si
1,2,Super Mario Bros.,Platform,NaN,NES,Nintendo,Nintendo EAD,10.0,NaN,40.24,NaN,NaN,NaN,NaN,NaN,1985.0,Recomendado,No
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,37.14,NaN,NaN,NaN,NaN,NaN,2008.0,Recomendado,Si
3,4,PlayerUnknown's Battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,36.60,NaN,NaN,NaN,NaN,NaN,2017.0,Sin Calificar,No
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,33.09,NaN,NaN,NaN,NaN,NaN,2009.0,Recomendado,Si

In [16]:
df.shape

(55792, 18)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55792 entries, 0 to 55791
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Rank                         55792 non-null  int64
 1   Name                         55792 non-null  object
 2   Genre                        55792 non-null  object
 3   ESRB_Rating                  23623 non-null  object
 4   Platform                     55792 non-null  object
 5   Publisher                    55792 non-null  object
 6   Developer                    55775 non-null  object
 7   Critic_Score                 6536 non-null   float64
 8   User_Score                   335 non-null    float64
 9   Total_Shipped                1827 non-null   float64
 10  Global_Sales                 19415 non-null  float64
 11  NA_Sales                     12964 non-null  float64
 12  PAL_Sales                    13189 non-null  float64
 13  JP_Sales                     7043 non-null   float64
 14  Other_Sales                  15522 non-null  float64
 15  Year                         54813 non-null  float64
 16  Recomendado_por_la_critica?  55792 non-null  object
 17  Apto_para_todo_publico?      55792 non-null  object
dtypes: float64(9), int64(1), object(8)
memory usage: 7.7+ MB

In [18]:
df.describe()

,Rank,Critic_Score,User_Score,Total_Shipped,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year
count,55792.000000,6536.000000,335.000000,1827.000000,19415.000000,12964.000000,13189.000000,7043.000000,15522.000000,54813.000000
mean,27896.500000,7.213709,8.253433,1.887258,0.365503,0.275541,0.155263,0.110402,0.044719,2005.659095
std,16105.907446,1.454079,1.401489,4.195693,0.833022,0.512809,0.399257,0.184673,0.129554,8.355585
min,1.000000,1.000000,2.000000,0.030000,0.000000,0.000000,0.000000,0.000000,0.000000,1970.000000
25%,13948.750000,6.400000,7.800000,0.200000,0.030000,0.050000,0.010000,0.020000,0.000000,2000.000000
50%,27896.500000,7.500000,8.500000,0.590000,0.120000,0.120000,0.040000,0.050000,0.010000,2008.000000
75%,41844.250000,8.300000,9.100000,1.800000,0.360000,0.290000,0.140000,0.120000,0.040000,2011.000000
max,55792.000000,10.000000,10.000000,82.860000,20.320000,9.760000,9.850000,2.690000,3.120000,2020.000000

In [19]:
import numpy as np

# Convierto 'Year' a numérico, manejando 'nan' como NaN y luego a Int64 (entero con soporte para nulos)
df['Year'] = pd.to_numeric(df['Year'], errors='coerce').astype(pd.Int64Dtype())

#Chequeo el cambio
display(df.dtypes)
#Miro las primeras filas para ver como quedó
display(df.head())
df.describe()

Rank                             int64
Name                            object
Genre                           object
ESRB_Rating                     object
Platform                        object
Publisher                       object
Developer                       object
Critic_Score                   float64
User_Score                     float64
Total_Shipped                  float64
Global_Sales                   float64
NA_Sales                       float64
PAL_Sales                      float64
JP_Sales                       float64
Other_Sales                    float64
Year                             Int64
Recomendado_por_la_critica?     object
Apto_para_todo_publico?         object
dtype: object

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer,Critic_Score,User_Score,Total_Shipped,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year,Recomendado_por_la_critica?,Apto_para_todo_publico?
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,82.86,NaN,NaN,NaN,NaN,NaN,2006,Recomendado,Si
1,2,Super Mario Bros.,Platform,NaN,NES,Nintendo,Nintendo EAD,10.0,NaN,40.24,NaN,NaN,NaN,NaN,NaN,1985,Recomendado,No
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,37.14,NaN,NaN,NaN,NaN,NaN,2008,Recomendado,Si
3,4,PlayerUnknown's Battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,36.60,NaN,NaN,NaN,NaN,NaN,2017,Sin Calificar,No
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,33.09,NaN,NaN,NaN,NaN,NaN,2009,Recomendado,Si

,Rank,Critic_Score,User_Score,Total_Shipped,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year
count,55792.000000,6536.000000,335.000000,1827.000000,19415.000000,12964.000000,13189.000000,7043.000000,15522.000000,54813.0
mean,27896.500000,7.213709,8.253433,1.887258,0.365503,0.275541,0.155263,0.110402,0.044719,2005.659095
std,16105.907446,1.454079,1.401489,4.195693,0.833022,0.512809,0.399257,0.184673,0.129554,8.355585
min,1.000000,1.000000,2.000000,0.030000,0.000000,0.000000,0.000000,0.000000,0.000000,1970.0
25%,13948.750000,6.400000,7.800000,0.200000,0.030000,0.050000,0.010000,0.020000,0.000000,2000.0
50%,27896.500000,7.500000,8.500000,0.590000,0.120000,0.120000,0.040000,0.050000,0.010000,2008.0
75%,41844.250000,8.300000,9.100000,1.800000,0.360000,0.290000,0.140000,0.120000,0.040000,2011.0
max,55792.000000,10.000000,10.000000,82.860000,20.320000,9.760000,9.850000,2.690000,3.120000,2020.0

Ahora que la columna `Year` es de tipo `Int64` (entero que soporta valores nulos), la operación de filtrado `df['Year'] < 1990` funciona correctamente.

In [20]:
# Calculo el porcentaje de nulos por columna
porcentaje_nulos = df.isnull().mean() * 100

print(porcentaje_nulos)

Rank                            0.000000
Name                            0.000000
Genre                           0.000000
ESRB_Rating                    57.658804
Platform                        0.000000
Publisher                       0.000000
Developer                       0.030470
Critic_Score                   88.285059
User_Score                     99.399555
Total_Shipped                  96.725337
Global_Sales                   65.201104
NA_Sales                       76.763694
PAL_Sales                      76.360410
JP_Sales                       87.376326
Other_Sales                    72.178807
Year                            1.754732
Recomendado_por_la_critica?     0.000000
Apto_para_todo_publico?         0.000000
dtype: float64

In [21]:
#Ordeno por porcentaje de valores nulos

porcentaje_nulos.sort_values(ascending=False)

User_Score                     99.399555
Total_Shipped                  96.725337
Critic_Score                   88.285059
JP_Sales                       87.376326
NA_Sales                       76.763694
PAL_Sales                      76.360410
Other_Sales                    72.178807
Global_Sales                   65.201104
ESRB_Rating                    57.658804
Year                            1.754732
Developer                       0.030470
Rank                            0.000000
Name                            0.000000
Publisher                       0.000000
Platform                        0.000000
Genre                           0.000000
Recomendado_por_la_critica?     0.000000
Apto_para_todo_publico?         0.000000
dtype: float64

##Saneamiento y selección

In [22]:
df.shape

(55792, 18)

In [23]:
#Al revisar con df.head(), veo que Global Sales contiene nulos, evaluo la cantidad:

filas_global_sales_nulo = df['Global_Sales'].isnull().sum()

print(f"Número de filas donde Global_Sales es nulo: {filas_global_sales_nulo}")

Número de filas donde Global_Sales es nulo: 36377

##Filtro

In [24]:
#Miro las filas en donde Global_Sales es nulo, detecto que si Global Sales es nulo, Total_Shipped tiene valores.

display(df[df['Global_Sales'].isnull()])

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer,Critic_Score,User_Score,Total_Shipped,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year,Recomendado_por_la_critica?,Apto_para_todo_publico?
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,82.86,NaN,NaN,NaN,NaN,NaN,2006,Recomendado,Si
1,2,Super Mario Bros.,Platform,NaN,NES,Nintendo,Nintendo EAD,10.0,NaN,40.24,NaN,NaN,NaN,NaN,NaN,1985,Recomendado,No
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,37.14,NaN,NaN,NaN,NaN,NaN,2008,Recomendado,Si
3,4,PlayerUnknown's Battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,36.60,NaN,NaN,NaN,NaN,NaN,2017,Sin Calificar,No
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,33.09,NaN,NaN,NaN,NaN,NaN,2009,Recomendado,Si
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55787,55788,Indivisible,Role-Playing,NaN,PC,505 Games,Lab Zero Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,Sin Calificar,No
55788,55789,Lost Ember,Adventure,RP,PC,Mooneye Studios,Mooneye Studios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,Sin Calificar,No
55789,55790,Lost Ember,Adventure,RP,PS4,Mooneye Studios,Mooneye Studios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,Sin Calificar,No
55790,55791,Lost Ember,Adventure,RP,XOne,Mooneye Studios,Mooneye Studios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,Sin Calificar,No
55791,55792,Falcon Age,Action-Adventure,NaN,PS4,Unknown,Outerloop Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,Sin Calificar,No

In [25]:

#Detecto que si Total Shipped es Nulo, tengo valores Siempre en Global Sales, por lo que reemplazo los valores de total Shipped en Global Sales si los valores son nulos.

df['Global_Sales'] = df['Global_Sales'].fillna(df['Total_Shipped'])

##Saneamiento 1

In [26]:
#Me deshago de la columna Total Shipped para evitar confusiones

df.drop('Total_Shipped', axis=1, inplace=True)
display(df.head())

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer,Critic_Score,User_Score,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year,Recomendado_por_la_critica?,Apto_para_todo_publico?
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,82.86,NaN,NaN,NaN,NaN,2006,Recomendado,Si
1,2,Super Mario Bros.,Platform,NaN,NES,Nintendo,Nintendo EAD,10.0,NaN,40.24,NaN,NaN,NaN,NaN,1985,Recomendado,No
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,37.14,NaN,NaN,NaN,NaN,2008,Recomendado,Si
3,4,PlayerUnknown's Battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,36.60,NaN,NaN,NaN,NaN,2017,Sin Calificar,No
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,33.09,NaN,NaN,NaN,NaN,2009,Recomendado,Si

In [27]:
#Miro si existen outliers en la columna Year del dataset
df['Year'].unique()

<IntegerArray>
[2006, 1985, 2008, 2017, 2009, 1998, 1989, 2010, 2007, 2005, 2000, 1991, 2013,
 2014, 2004, 2011, 1990, 2003, 2002, 2016, 2015, 2001, 1999, 2018, 2012, 1996,
 1992, 1993, 1997, 1994, 1982, 1988, 1987, 1995, 1981, 1986, 1978, 1983, 2020,
 1984, 1977, 2019, 1980, 1970, 1979, <NA>, 1975, 1973]
Length: 48, dtype: Int64

In [28]:
pd.Series(df['Year'].unique()).sort_values(ascending=True)

43    1970
47    1973
46    1975
40    1977
36    1978
44    1979
42    1980
34    1981
30    1982
37    1983
39    1984
1     1985
35    1986
32    1987
31    1988
6     1989
16    1990
11    1991
26    1992
27    1993
29    1994
33    1995
25    1996
28    1997
5     1998
22    1999
10    2000
21    2001
18    2002
17    2003
14    2004
9     2005
0     2006
8     2007
2     2008
4     2009
7     2010
15    2011
24    2012
12    2013
13    2014
20    2015
19    2016
3     2017
23    2018
41    2019
38    2020
45    <NA>
dtype: Int64

In [29]:
df['Year'].value_counts().sort_index(ascending=True)

Year
1970     104
1973       1
1975       1
1977      12
1978      48
1979       5
1980      35
1981      37
1982     214
1983     300
1984      88
1985      93
1986     146
1987     259
1988     282
1989     436
1990     666
1991     786
1992     935
1993    1043
1994    1163
1995    1162
1996    1220
1997    1030
1998    1094
1999    1285
2000    1561
2001    1493
2002    1736
2003    1738
2004    1611
2005    1821
2006    2112
2007    2573
2008    2979
2009    4507
2010    3661
2011    3489
2012    1560
2013    1723
2014    2905
2015    1633
2016    1238
2017    1486
2018    1482
2019     729
2020     331
Name: count, dtype: Int64

Detecto que a partir del año 1990 el dataset me arroja cantidad de registros uniforme y representativa

##Saneamiento 2

In [30]:
#Borro filas donde Year sea nulo

df.dropna(subset=['Year'])

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer,Critic_Score,User_Score,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year,Recomendado_por_la_critica?,Apto_para_todo_publico?
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,82.86,NaN,NaN,NaN,NaN,2006,Recomendado,Si
1,2,Super Mario Bros.,Platform,NaN,NES,Nintendo,Nintendo EAD,10.0,NaN,40.24,NaN,NaN,NaN,NaN,1985,Recomendado,No
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,37.14,NaN,NaN,NaN,NaN,2008,Recomendado,Si
3,4,PlayerUnknown's Battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,36.60,NaN,NaN,NaN,NaN,2017,Sin Calificar,No
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,33.09,NaN,NaN,NaN,NaN,2009,Recomendado,Si
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55786,55787,In the Valley of Gods,Adventure,NaN,PC,Campo Santo,Campo Santo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,Sin Calificar,No
55787,55788,Indivisible,Role-Playing,NaN,PC,505 Games,Lab Zero Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,Sin Calificar,No
55788,55789,Lost Ember,Adventure,RP,PC,Mooneye Studios,Mooneye Studios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,Sin Calificar,No
55789,55790,Lost Ember,Adventure,RP,PS4,Mooneye Studios,Mooneye Studios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,Sin Calificar,No
55790,55791,Lost Ember,Adventure,RP,XOne,Mooneye Studios,Mooneye Studios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,Sin Calificar,No

##Filtro

In [31]:
# Filtrar el DataFrame para años anteriores a 1990
display(df[df['Year'] < 1990])

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer,Critic_Score,User_Score,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year,Recomendado_por_la_critica?,Apto_para_todo_publico?
1,2,Super Mario Bros.,Platform,NaN,NES,Nintendo,Nintendo EAD,10.0,NaN,40.24,NaN,NaN,NaN,NaN,1985,Recomendado,No
7,8,Tetris,Puzzle,E,GB,Nintendo,Bullet Proof Software,NaN,NaN,30.26,NaN,NaN,NaN,NaN,1989,Sin Calificar,Si
10,11,Duck Hunt,Shooter,NaN,NES,Nintendo,Nintendo R&D1,NaN,NaN,28.31,NaN,NaN,NaN,NaN,1985,Sin Calificar,No
23,24,Super Mario Land,Platform,E,GB,Nintendo,Nintendo R&D1,NaN,NaN,18.14,NaN,NaN,NaN,NaN,1989,Sin Calificar,Si
125,126,Pac-Man,Puzzle,NaN,2600,Atari,Atari,NaN,NaN,7.70,NaN,NaN,NaN,NaN,1982,Sin Calificar,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55686,55687,World Championship Baseball,Sports,NaN,Int,INTV Corporation,APh Technological Consulting,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1986,Sin Calificar,No
55688,55689,World Cup Soccer,Sports,NaN,Int,Dextell Ltd.,Mattel Electronics France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1985,Sin Calificar,No
55700,55701,World Series Major League Baseball,Sports,NaN,Int,Mattel Electronics,Mattel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1983,Sin Calificar,No
55707,55708,Worm Whomper,Shooter,NaN,Int,Activision,Cheshire Engineering,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1983,Sin Calificar,No
55770,55771,Zaxxon,Shooter,NaN,Int,Coleco,Coleco,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1983,Sin Calificar,No

##Saneamiento 3

In [32]:
# Elimino las filas donde el año es anterior a 1990
df = df[df['Year'] >= 1990]

In [33]:
# Verifico la nueva forma del DataFrame después de la eliminación
display(df.shape)

(52752, 17)

In [34]:
# Y las primeras filas para confirmar los cambios
display(df.head())

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer,Critic_Score,User_Score,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year,Recomendado_por_la_critica?,Apto_para_todo_publico?
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,82.86,NaN,NaN,NaN,NaN,2006,Recomendado,Si
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,37.14,NaN,NaN,NaN,NaN,2008,Recomendado,Si
3,4,PlayerUnknown's Battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,36.60,NaN,NaN,NaN,NaN,2017,Sin Calificar,No
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,33.09,NaN,NaN,NaN,NaN,2009,Recomendado,Si
5,6,Pokemon Red / Green / Blue Version,Role-Playing,E,GB,Nintendo,Game Freak,9.4,NaN,31.38,NaN,NaN,NaN,NaN,1998,Recomendado,Si

In [35]:
# Cuento la cantidad de celdas con 'RP' en la columna 'ESRB_Rating'
count_rp = len(df[df['ESRB_Rating'] == 'RP'])
print(f"Número de filas con ESRB_Rating 'RP': {count_rp}")

Número de filas con ESRB_Rating 'RP': 323

RP en ESRB_Rating equivale a = Rating pendiente, por lo que, para limpiar y unificar, reemplazo los valores nulos y RP por Sin clasificar

##Saneamiento 4

In [36]:
df['ESRB_Rating'] = df['ESRB_Rating'].fillna('Sin clasificar')
df['ESRB_Rating'] = df['ESRB_Rating'].replace('RP', 'Sin clasificar')

In [37]:
display(df.head())

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer,Critic_Score,User_Score,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year,Recomendado_por_la_critica?,Apto_para_todo_publico?
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,82.86,NaN,NaN,NaN,NaN,2006,Recomendado,Si
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,37.14,NaN,NaN,NaN,NaN,2008,Recomendado,Si
3,4,PlayerUnknown's Battlegrounds,Shooter,Sin clasificar,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,36.60,NaN,NaN,NaN,NaN,2017,Sin Calificar,No
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,33.09,NaN,NaN,NaN,NaN,2009,Recomendado,Si
5,6,Pokemon Red / Green / Blue Version,Role-Playing,E,GB,Nintendo,Game Freak,9.4,NaN,31.38,NaN,NaN,NaN,NaN,1998,Recomendado,Si

In [38]:
cantidad_nulos_esrb = df['ESRB_Rating'].isnull().sum()
print(f"Número de filas con ESRB_Rating nulo: {cantidad_nulos_esrb}")

Número de filas con ESRB_Rating nulo: 0

In [39]:
#Creo una columna para filtrar si tengo registros de ventas distribuidos regionalmente
df['Ventas_Distribuidas_Regionalmente?'] = np.where(
    (df['Global_Sales'].notna()) &
    (df['NA_Sales'].isna()) &
    (df['PAL_Sales'].isna()) &
    (df['JP_Sales'].isna()) &
    (df['Other_Sales'].isna()),
    'No', 'Si'
)
display(df.head())

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer,Critic_Score,User_Score,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year,Recomendado_por_la_critica?,Apto_para_todo_publico?,Ventas_Distribuidas_Regionalmente?
0,1,Wii Sports,Sports,E,Wii,Nintendo,Nintendo EAD,7.7,NaN,82.86,NaN,NaN,NaN,NaN,2006,Recomendado,Si,No
2,3,Mario Kart Wii,Racing,E,Wii,Nintendo,Nintendo EAD,8.2,9.1,37.14,NaN,NaN,NaN,NaN,2008,Recomendado,Si,No
3,4,PlayerUnknown's Battlegrounds,Shooter,Sin clasificar,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,36.60,NaN,NaN,NaN,NaN,2017,Sin Calificar,No,No
4,5,Wii Sports Resort,Sports,E,Wii,Nintendo,Nintendo EAD,8.0,8.8,33.09,NaN,NaN,NaN,NaN,2009,Recomendado,Si,No
5,6,Pokemon Red / Green / Blue Version,Role-Playing,E,GB,Nintendo,Game Freak,9.4,NaN,31.38,NaN,NaN,NaN,NaN,1998,Recomendado,Si,No

##Filtro booleano

In [40]:
display(df[df['Ventas_Distribuidas_Regionalmente?'] == 'Si'])

,Rank,Name,Genre,ESRB_Rating,Platform,Publisher,Developer,Critic_Score,User_Score,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year,Recomendado_por_la_critica?,Apto_para_todo_publico?,Ventas_Distribuidas_Regionalmente?
19,20,Grand Theft Auto V,Action,M,PS3,Rockstar Games,Rockstar North,9.4,NaN,20.32,6.37,9.85,0.99,3.12,2013,Recomendado,No,Si
20,21,Grand Theft Auto V,Action,M,PS4,Rockstar Games,Rockstar North,9.7,NaN,19.39,6.06,9.71,0.60,3.02,2014,Recomendado,No,Si
30,31,Grand Theft Auto: Vice City,Action,M,PS2,Rockstar Games,Rockstar North,9.6,NaN,16.15,8.41,5.49,0.47,1.78,2002,Recomendado,No,Si
32,33,Grand Theft Auto V,Action,M,X360,Rockstar Games,Rockstar North,NaN,NaN,15.86,9.06,5.33,0.06,1.42,2013,Sin Calificar,No,Si
34,35,Call of Duty: Black Ops 3,Shooter,M,PS4,Activision,Treyarch,NaN,NaN,15.09,6.18,6.05,0.41,2.44,2015,Sin Calificar,No,Si
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55786,55787,In the Valley of Gods,Adventure,Sin clasificar,PC,Campo Santo,Campo Santo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,Sin Calificar,No,Si
55787,55788,Indivisible,Role-Playing,Sin clasificar,PC,505 Games,Lab Zero Games,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,Sin Calificar,No,Si
55788,55789,Lost Ember,Adventure,Sin clasificar,PC,Mooneye Studios,Mooneye Studios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,Sin Calificar,No,Si
55789,55790,Lost Ember,Adventure,Sin clasificar,PS4,Mooneye Studios,Mooneye Studios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,Sin Calificar,No,Si
55790,55791,Lost Ember,Adventure,Sin clasificar,XOne,Mooneye Studios,Mooneye Studios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019,Sin Calificar,No,Si

Resumen del análisis: Se refuta la teoría de las ventas digitales y físicas, la diferencia entre la cantidad de nulos de Total Shipped y Global Sales responde a que en algunos casos la cantidad de ventas está distribuida por región y en otras no.

-La columna Year no se detectó como fecha por lo que se debió recurrir a Numpy para modificar el tipo de variable.

-Si bien el dataset contiene datos desde el 1970, la cantidad de registros no mantiene una lógica uniforme hasta al menos el año 1990.

Las columnas clave serían: Global Sales, (NA_Sales,PAL_Sales,JP_Sales,Other_Sales - En los casos que se cuente con la apertura por región) Name, Genre, Platform, Year.